/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ServicesImport } from './routes/services'
import { Route as RegisterImport } from './routes/register'
import { Route as LoginImport } from './routes/login'
import { Route as InstructorsImport } from './routes/instructors'
import { Route as ContactImport } from './routes/contact'
import { Route as AboutImport } from './routes/about'
import { Route as catchAllImport } from './routes/__catch-all'
import { Route as IndexImport } from './routes/index'
import { Route as AuthAuthImport } from './routes/_auth/_auth'
import { Route as AuthAuthSettingsImport } from './routes/_auth/_auth.settings'
import { Route as AuthAuthRegisterImport } from './routes/_auth/_auth.register'
import { Route as AuthAuthProfileImport } from './routes/_auth/_auth.profile'
import { Route as AuthAuthPaymentHistoryImport } from './routes/_auth/_auth.payment-history'
import { Route as AuthAuthPaymentImport } from './routes/_auth/_auth.payment'
import { Route as AuthAuthMembershipPlansImport } from './routes/_auth/_auth.membership-plans'
import { Route as AuthAuthMembersImport } from './routes/_auth/_auth.members'
import { Route as AuthAuthDashboardImport } from './routes/_auth/_auth.dashboard'
import { Route as AuthAuthCheckInImport } from './routes/_auth/_auth.check-in'
import { Route as AuthAuthAdminImport } from './routes/_auth/_auth.admin'

// Create/Update Routes

const ServicesRoute = ServicesImport.update({
  path: '/services',
  getParentRoute: () => rootRoute,
} as any)

const RegisterRoute = RegisterImport.update({
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const InstructorsRoute = InstructorsImport.update({
  path: '/instructors',
  getParentRoute: () => rootRoute,
} as any)

const ContactRoute = ContactImport.update({
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const catchAllRoute = catchAllImport.update({
  id: '/__catch-all',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthAuthRoute = AuthAuthImport.update({
  id: '/_auth/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AuthAuthSettingsRoute = AuthAuthSettingsImport.update({
  path: '/settings',
  getParentRoute: () => AuthAuthRoute,
} as any)

const AuthAuthRegisterRoute = AuthAuthRegisterImport.update({
  path: '/register',
  getParentRoute: () => AuthAuthRoute,
} as any)

const AuthAuthProfileRoute = AuthAuthProfileImport.update({
  path: '/profile',
  getParentRoute: () => AuthAuthRoute,
} as any)

const AuthAuthPaymentHistoryRoute = AuthAuthPaymentHistoryImport.update({
  path: '/payment-history',
  getParentRoute: () => AuthAuthRoute,
} as any)

const AuthAuthPaymentRoute = AuthAuthPaymentImport.update({
  path: '/payment',
  getParentRoute: () => AuthAuthRoute,
} as any)

const AuthAuthMembershipPlansRoute = AuthAuthMembershipPlansImport.update({
  path: '/membership-plans',
  getParentRoute: () => AuthAuthRoute,
} as any)

const AuthAuthMembersRoute = AuthAuthMembersImport.update({
  path: '/members',
  getParentRoute: () => AuthAuthRoute,
} as any)

const AuthAuthDashboardRoute = AuthAuthDashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => AuthAuthRoute,
} as any)

const AuthAuthCheckInRoute = AuthAuthCheckInImport.update({
  path: '/check-in',
  getParentRoute: () => AuthAuthRoute,
} as any)

const AuthAuthAdminRoute = AuthAuthAdminImport.update({
  path: '/admin',
  getParentRoute: () => AuthAuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/__catch-all': {
      id: '/__catch-all'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof catchAllImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactImport
      parentRoute: typeof rootRoute
    }
    '/instructors': {
      id: '/instructors'
      path: '/instructors'
      fullPath: '/instructors'
      preLoaderRoute: typeof InstructorsImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesImport
      parentRoute: typeof rootRoute
    }
    '/_auth/_auth': {
      id: '/_auth/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthAuthImport
      parentRoute: typeof rootRoute
    }
    '/_auth/_auth/admin': {
      id: '/_auth/_auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAuthAdminImport
      parentRoute: typeof AuthAuthImport
    }
    '/_auth/_auth/check-in': {
      id: '/_auth/_auth/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof AuthAuthCheckInImport
      parentRoute: typeof AuthAuthImport
    }
    '/_auth/_auth/dashboard': {
      id: '/_auth/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthAuthDashboardImport
      parentRoute: typeof AuthAuthImport
    }
    '/_auth/_auth/members': {
      id: '/_auth/_auth/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthAuthMembersImport
      parentRoute: typeof AuthAuthImport
    }
    '/_auth/_auth/membership-plans': {
      id: '/_auth/_auth/membership-plans'
      path: '/membership-plans'
      fullPath: '/membership-plans'
      preLoaderRoute: typeof AuthAuthMembershipPlansImport
      parentRoute: typeof AuthAuthImport
    }
    '/_auth/_auth/payment': {
      id: '/_auth/_auth/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof AuthAuthPaymentImport
      parentRoute: typeof AuthAuthImport
    }
    '/_auth/_auth/payment-history': {
      id: '/_auth/_auth/payment-history'
      path: '/payment-history'
      fullPath: '/payment-history'
      preLoaderRoute: typeof AuthAuthPaymentHistoryImport
      parentRoute: typeof AuthAuthImport
    }
    '/_auth/_auth/profile': {
      id: '/_auth/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthAuthProfileImport
      parentRoute: typeof AuthAuthImport
    }
    '/_auth/_auth/register': {
      id: '/_auth/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthAuthRegisterImport
      parentRoute: typeof AuthAuthImport
    }
    '/_auth/_auth/settings': {
      id: '/_auth/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthAuthSettingsImport
      parentRoute: typeof AuthAuthImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AboutRoute,
  ContactRoute,
  InstructorsRoute,
  LoginRoute,
  RegisterRoute,
  ServicesRoute,
  AuthAuthRoute: AuthAuthRoute.addChildren({
    AuthAuthAdminRoute,
    AuthAuthCheckInRoute,
    AuthAuthDashboardRoute,
    AuthAuthMembersRoute,
    AuthAuthMembershipPlansRoute,
    AuthAuthPaymentRoute,
    AuthAuthPaymentHistoryRoute,
    AuthAuthProfileRoute,
    AuthAuthRegisterRoute,
    AuthAuthSettingsRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/__catch-all",
        "/about",
        "/contact",
        "/instructors",
        "/login",
        "/register",
        "/services",
        "/_auth/_auth"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/__catch-all": {
      "filePath": "__catch-all.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/contact": {
      "filePath": "contact.tsx"
    },
    "/instructors": {
      "filePath": "instructors.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/services": {
      "filePath": "services.tsx"
    },
    "/_auth/_auth": {
      "filePath": "_auth/_auth.tsx",
      "children": [
        "/_auth/_auth/admin",
        "/_auth/_auth/check-in",
        "/_auth/_auth/dashboard",
        "/_auth/_auth/members",
        "/_auth/_auth/membership-plans",
        "/_auth/_auth/payment",
        "/_auth/_auth/payment-history",
        "/_auth/_auth/profile",
        "/_auth/_auth/register",
        "/_auth/_auth/settings"
      ]
    },
    "/_auth/_auth/admin": {
      "filePath": "_auth/_auth.admin.tsx",
      "parent": "/_auth/_auth"
    },
    "/_auth/_auth/check-in": {
      "filePath": "_auth/_auth.check-in.tsx",
      "parent": "/_auth/_auth"
    },
    "/_auth/_auth/dashboard": {
      "filePath": "_auth/_auth.dashboard.tsx",
      "parent": "/_auth/_auth"
    },
    "/_auth/_auth/members": {
      "filePath": "_auth/_auth.members.tsx",
      "parent": "/_auth/_auth"
    },
    "/_auth/_auth/membership-plans": {
      "filePath": "_auth/_auth.membership-plans.tsx",
      "parent": "/_auth/_auth"
    },
    "/_auth/_auth/payment": {
      "filePath": "_auth/_auth.payment.tsx",
      "parent": "/_auth/_auth"
    },
    "/_auth/_auth/payment-history": {
      "filePath": "_auth/_auth.payment-history.tsx",
      "parent": "/_auth/_auth"
    },
    "/_auth/_auth/profile": {
      "filePath": "_auth/_auth.profile.tsx",
      "parent": "/_auth/_auth"
    },
    "/_auth/_auth/register": {
      "filePath": "_auth/_auth.register.tsx",
      "parent": "/_auth/_auth"
    },
    "/_auth/_auth/settings": {
      "filePath": "_auth/_auth.settings.tsx",
      "parent": "/_auth/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
